#DROP SCHEMA IF EXISTS `gqshop`;
#CREATE SCHEMA IF NOT EXISTS `gqshop` ;

CREATE TABLE IF NOT EXISTS `gqshop`.`food_menu` (
  `id` VARCHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(2048) NULL DEFAULT NULL,
  `image_url` VARCHAR(2048) NULL DEFAULT NULL,
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idx_UNIQUE` (`idx` ASC));

CREATE TABLE IF NOT EXISTS `gqshop`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(36) NOT NULL DEFAULT 'todo',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));

CREATE TABLE IF NOT EXISTS `gqshop`.`orders_has_food_menu` (
  `idx` INT(11) NOT NULL AUTO_INCREMENT,
  `orders_id` INT(11) NOT NULL,
  `food_menu_id` VARCHAR(36) NOT NULL,
  `amount` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`idx`));